routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**
 * Website routes.
 */
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Route::get('/home', 'HomeController@index')->name('home');

/*
 * Internal API
 */
Route::group(['namespace' => 'Website'], function () {
    Route::get('/', 'SiteController@frontPage')->name('website.frontpage');
    Route::get('/sharePost', 'PostController@sharePost')->name('website.sharePost');
    Route::get('/blog', 'PostController@blog')->name('website.blog');
    Route::get('/nota/{post}', 'PostController@article')->name('website.article');
    Route::resource('profile', 'ProfileController')->only(['store', 'create', 'edit']);
    Route::get('/match/results', 'MatchsController@results')->name('games.results');
    Route::get('/match/results/{game}', 'MatchsController@single')->name('games.single');
    Route::get('/section/{section}', 'SectionController@show')->name('section.show');
    Route::get('leagues/{competition}', 'SiteController@showLeague')->name('website.competition.show');
});

Route::group(['prefix' => 'helium', 'namespace' => 'Helium'], function () {
    // Getters
    Route::get('/formal', 'APIController@formal');
    Route::post('article/bodyContent/image', 'APIController@bodyImage');
    Route::post('newArticle', 'PostController@store');
    Route::put('/aprove/article/{post}', 'PostController@approve')->name('posts.approve');
    Route::put('/review/article/{post}', 'PostController@review')->name('posts.review');
    Route::get('/teams/{team}/edit', 'DataController@editTeam')->name('team.edit');
    Route::put('/teams/{team}/update', 'DataController@updateTeam')->name('team.update');
    Route::get('/add-result/games/{game}', 'GamesController@create')->name('games.result');
    Route::post('/add-result/games/{game}', 'GamesController@store')->name('games.result-add');
    Route::get('/games/{game}', 'GamesController@show')->name('games.show');
    Route::get('/games/{game}/edit', 'GamesController@edit')->name('games.edit');
    Route::post('/games/{game}/edit', 'GamesController@update')->name('games.update');

    Route::middleware('auth')->prefix('sections/{section}/control')->group(function () {
        Route::resource('sponsors', 'SponsorController');
    });
});

Route::middleware('auth')->prefix('helium')->namespace('Helium')->group(function () {
    Route::get('/', 'HomeController@index')->name('helium.dashboard');
    Route::resource('posts', 'PostController');
    Route::resource('competitions', 'CompetitionsController');
    Route::resource('sections', 'SectionsController');
    Route::get('details/{competition}/create', 'DetailsController@create')->name('details.create');
    Route::post('details/{competition}/create', 'DetailsController@store')->name('details.store');
    Route::get('details/{detail}/edit', 'DetailsController@edit')->name('details.edit');
    Route::put('details/{detail}', 'DetailsController@update')->name('details.update');
    Route::get('board/generate/season/{season}', 'BoardController@init')->name('board.init');
    Route::get('board/{leaderboard}/edit', 'BoardController@edit')->name('board.edit');
    Route::put('board/{leaderboard}', 'BoardController@update')->name('board.update');
    Route::resource('products', 'ProductController');
    Route::get('wizards', 'WizardController@entry')->name('wizards');
    Route::namespace('Wizards') ->group(function () {
        Route::get('wizards/new_season', 'NewSeasonController@start')->name('wizards.new_season');
        Route::post('/wizards/new_season/{season}/games', 'NewSeasonController@saveGames')->name('wizard.load.games');
    });
});

Route::group(['namespace' => 'InternalAPI'], function () {
    Route::get('/products/list', 'ProductController@index')->name('product.list');
});

/*
 * Providers
 */

//Routes for socialite
Route::get('auth/{provider}', 'LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'LoginController@handleProviderCallback');

app/Http/Controllers/Helium/APIController.php
<?php

namespace App\Http\Controllers\Helium;

use App\Section;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use TCG\Voyager\Models\Category;
use App\Http\Controllers\Controller;
use App\Http\Resources\FormalCollection;

class APIController extends Controller
{
    /**
     * APIController constructor.
     */
    public function __construct()
    {
        $this->middleware('api');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function formal(Request $request)
    {
        if (! $request->ajax()) {
            abort(404);
        }

        $categories = Category::all();
        $sections = Section::activated()->get();

        $da = [
            'categories' => $categories,
            'sections' => $sections,
        ];

        $d = collect($da);

        return new FormalCollection($d);
    }

    /**
     * AJAX post body image upload.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function bodyImage(Request $request)
    {
        $request->validate([
            'image' => 'required|image'
        ]);

        $img = Image::make($request->file('image'))->encode('jpg', 75);

        $timestamp = (new \DateTime())->getTimestamp();

        $hashed_path = "posts/body/cdj-" . md5(uniqid() . str_random(25)) . "-{$timestamp}.jpg";

        try {
            Storage::disk(config('voyager.storage.disk'))->put($hashed_path, $img);

        } catch (\Exception $e) {
            throw $e;
        }

        return response()->json(['success' => true, 'url' => "/storage/{$hashed_path}"]);
    }
}

app/Http/Controllers/Helium/BoardController.php
<?php

namespace App\Http\Controllers\Helium;

use App\Leaderboard;
use App\Season;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BoardController extends Controller
{
    /**
     * BoardController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Initializes a leaderboard for the given season.
     *
     * @param Season $season
     * @return \Illuminate\Http\RedirectResponse
     */
    public function init(Season $season)
    {
        if (is_null($season->teams)) return redirect()->route('competitions.index');

        $teams = $season->teams;

        $season->load(['competition', 'competition.detail']);

        if ($season->competition->detail->is_cup) {
            $this->createCupBoard($season, $teams);
        } else {
            $this->createLeagueBoard($season, $teams);
        }

        return redirect()->route('competitions.show', $season->competition->uuid);
    }

    /**
     * @param Season $season
     * @param $teams
     */
    protected function createLeagueBoard(Season $season, $teams)
    {
        $rank = 1;
        foreach ($teams->sortBy('name') as $team) {
           $season->board()->create([
                'external_competition_id' => $season->competition->external_id,
                'matchday' => 0,
                'position' => $rank,
                'external_team_id' => $team->external_id,
                'playedGames' => 0,
                'points' => 0,
                'goals' => 0,
                'goalsAgainst' => 0,
                'goalDifference' => 0,
                'wins' => 0,
                'draws' => 0,
                'losses' => 0,
                'group' => 'league',
            ]);
            $rank++;
        }
    }

    public function edit(Leaderboard $leaderboard)
    {
        $elements = $leaderboard->fieldType();
        $leaderboard->load('team');
        return view('helium.board.edit', compact('leaderboard', 'elements'));
    }

    public function update(Leaderboard $leaderboard, Request $request)
    {
        $leaderboard->update($request->all());

        return redirect()->route('competitions.show', $leaderboard->season->competition->uuid);
    }

    protected function createCupBoard($season, $teams)
    {
        $groups = range('A', 'H');
        $g = 0;
        $rank = 1;
        foreach ($teams->shuffle()->chunk(4) as $group) {
            foreach ($group as $team) {
                $season->board()->create([
                    'external_competition_id' => $season->competition->external_id,
                    'matchday' => 0,
                    'position' => $rank,
                    'external_team_id' => $team->external_id,
                    'playedGames' => 0,
                    'points' => 0,
                    'goals' => 0,
                    'goalsAgainst' => 0,
                    'goalDifference' => 0,
                    'wins' => 0,
                    'draws' => 0,
                    'losses' => 0,
                    'group' => $groups[$g],
                ]);
                $rank++;
            }
            $g++;
        }
    }
}

app/Http/Controllers/Helium/CompetitionsController.php
<?php

namespace App\Http\Controllers\Helium;

use App\Section;
use App\Competition;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class CompetitionsController extends Controller
{
    /**
     * @var string
     */
    const FILE_PATH = 'competitions';

    /**
     * @var string
     */
    protected $filesystem;

    public function __construct()
    {
        $this->middleware('auth');
        $this->filesystem = config('voyager.storage.disk');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $competitions = Competition::all();

        return view('helium.competitions.index', compact('competitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sections = Section::activated()->get();

        return view('helium.competitions.create', compact('sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'section_id' => 'required',
            'name' => 'required',
            'acronym' => 'required',
            'total_games' => 'required',
            'total_rounds' => 'required',
            'total_teams' => 'required',
            'league_logo' => 'image|required',
            'league_website' => 'required',
        ]);

        $path = $this->saveLogoInStorage($request->file('league_logo'));

        $timestamp = new \DateTime();

        $competition = Competition::create([
            'section_id' => $request->input('section_id'),
            'name' => $request->input('name'),
            'acronym' => $request->input('acronym'),
            'total_games' => $request->input('total_games'),
            'total_rounds' => $request->input('total_rounds'),
            'total_teams' => $request->input('total_teams'),
            'league_logo' => $path,
            'league_website' => $request->input('league_website'),
            'external_id' => $timestamp->getTimestamp(),
            'external_source' => 'Grupo Marotec'
        ]);

        return redirect()->route('details.create', $competition->id);
    }

    /**
     * Display the specified resource.
     *
     * @param Competition $competition
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Competition $competition)
    {
        $competition->load(['section', 'detail']);

        $season = $competition->seasons->where('is_current', true)->last();

        if ($season !== null) $season->load(['teams', 'games', 'board']);

        $elements = $competition->getFillable();

        return view('helium.competitions.show', compact('competition', 'elements', 'season'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Competition $competition
     * @return \Illuminate\Http\Response
     */
    public function edit(Competition $competition)
    {
        $sections = Section::activated()->get();

        return view('helium.competitions.edit', compact('competition', 'sections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Competition $competition
     * @return Response
     */
    public function update(Request $request, Competition $competition)
    {
        $request->validate([
            'section_id' => 'required',
            'name' => 'required',
            'acronym' => 'required',
            'total_games' => 'required',
            'total_rounds' => 'required',
            'total_teams' => 'required',
            'league_logo' => 'image',
            'league_website' => 'required',
            'is_open' => 'boolean'
        ]);

        if ($request->hasFile('league_logo')) {
            $path = $this->saveLogoInStorage($request->file('league_logo'));
            $competition->update(['league_logo' => $path]);
        }

        if ($request->has('is_open')) {
            $competition->update(['is_open' => (bool) $request->input('is_open')]);
        } else {
            $competition->update(['is_open' => false]);
        }

        $competition->update([
            'section_id' => $request->input('section_id'),
            'name' => $request->input('name'),
            'acronym' => $request->input('acronym'),
            'total_games' => $request->input('total_games'),
            'total_rounds' => $request->input('total_rounds'),
            'total_teams' => $request->input('total_teams'),
            'league_website' => $request->input('league_website'),
        ]);

        return redirect()->route('competitions.show', $competition->uuid);
    }

    /**
     * @param $file
     * @return mixed
     */
    protected function saveLogoInStorage($file)
    {
        $path = Storage::disk($this->filesystem)->putFile(self::FILE_PATH, $file);

        return $path;
    }
}

app/Http/Controllers/Helium/DataController.php
<?php

namespace App\Http\Controllers\Helium;

use App\Team;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class DataController extends Controller
{
    const TEAM_VALIDATION = [
        'name' => 'required|string|min:6',
        'acronym' => 'required|max:5|min:2|string',
        'shortName' => 'required|min:2|string',
        'team_logo' => 'sometimes|image',
        'active' => 'required'
    ];

    /**
     * DataController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param Team $team
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function editTeam(Team $team)
    {
        return view('helium.teams.edit', compact('team'));
    }

    /**
     * @param Team $team
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateTeam(Team $team, Request $request)
    {
        $request->validate(
            self::TEAM_VALIDATION
        );

        if ($file = $request->file('team_logo')) {
            $imgProcess = $this->upload($request, 'team_logo');
        } else {
            $imgProcess = ['success' => false, 'url' => ''];
        }

        if ($imgProcess['success']) {
            $team->update([
                'name' => $request->input('name'),
                'acronym' => $request->input('acronym'),
                'shortName' => $request->input('shortName'),
                'active' => (bool) $request->input('active'),
                'team_logo' => $imgProcess['url'],
            ]);
        } else {
            $team->update([
                'name' => $request->input('name'),
                'acronym' => $request->input('acronym'),
                'shortName' => $request->input('shortName'),
                'active' => (bool) $request->input('active'),
            ]);
        }

        return redirect()->route('competitions.show', $team->competition_id);
    }

    /**
     * @param Request $request
     * @param string $field
     * @return array
     */
    private function upload(Request $request, string $field): array
    {
        $img = Image::make($request->file($field))->encode('png', 75);

        $timestamp = (new \DateTime())->getTimestamp();

        $hashed_path = "teams/shields-" . md5(uniqid() . str_random(25)) . "-{$timestamp}.jpg";

        try {
            Storage::disk(config('voyager.storage.disk'))->put($hashed_path, $img);
        } catch (\Exception $e) {
            return ['success' => false, 'url' => ''];
        }
        return ['success' => true, 'url' => $hashed_path];
    }
}

app/Http/Controllers/Helium/WizardController.php
<?php

namespace App\Http\Controllers\Helium;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class WizardController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function entry()
    {
        return view('helium.wizards.index');
    }
}

resources/views/helium/sponsors/create.blade.php
@extends('helium.layout')

@section('content')
    <section class="section">
        <div class="container">
            <h4>Nuevo sponsor: {{ $section->name }}</h4>
            <div class="divider"></div>
            <form enctype="multipart/form-data" action="{{ route('sponsors.store', $section->slug) }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                <div class="input-field">
                    <input type="text" name="name" id="name">
                    <label for="name">Nombre</label>
                </div>

                <div class="input-field">
                    <input type="text" name="link" id="link">
                    <label for="link">Enlace de redireccion</label>
                </div>

                <div class="input-field">
                    <select name="zone" id="zone">
                        <option disabled selected>Elige el area de display</option>
                        <option value="banner">Banner principal</option>
                        <option value="matches">Barra de partidos</option>
                        <option value="stats">Cuadro sobre stats</option>
                        {{--<option value="feed">Feed de noticias</option>--}}
                        {{--<option value="feed">Feed de noticias</option>--}}
                        {{--<option value="mobile-menu">Menu de moviles</option>--}}
                        {{--<option value="mobile-fitlers">Secciones en movil</option>--}}
                        {{--<option value="b-posts">Banner en posts</option>--}}
                        {{--<option value="c-posts">Cuadro en posts</option>--}}
                    </select>
                </div>

                <div class="input-field">
                    <input type="text" class="datepicker" name="valid_from" id="valid_from">
                    <label for="valid_from">Inicio del sponsorship</label>
                </div>

                <div class="input-field">
                    <input type="text" class="datepicker" name="valid_to" id="valid_to">
                    <label for="valid_to">Fin del sponsorship</label>
                </div>

                <div class="file-field input-field">
                    <div class="btn">
                        <span>Imagen</span>
                        <input type="file" name="media">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                </div>

                <p>
                    <input type="checkbox" class="filled-in" id="filled-in-box" name="is_active" value="1"/>
                    <label for="filled-in-box">Activo</label>
                </p>
                <button type="submit" class="btn btn-full black white-text">
                    Guardar sponsor
                </button>
            </form>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 3, // Creates a dropdown of 15 years to control year,
            today: 'Hoy',
            clear: 'Cancelar',
            close: 'Aceptar',
            closeOnSelect: true,
            format: 'yyyy-mm-d'// Close upon selecting a date,
        });
        $(document).ready(function() {
            $('select').material_select();
        });
    </script>
@endsection

resources/views/helium/sponsors/edit.blade.php
@extends('helium.layout')

@section('content')

@endsection

resources/views/helium/sponsors/index.blade.php
@extends('helium.layout')

@section('content')
    <section class="section">
        <div class="container">
            <h4>Sponsors para: {{ $section->name }} <a class="btn black white-text right" href="{{ route('sponsors.create', $section->slug) }}">Agregar</a></h4>
            <div class="divider"></div>
            @if($sponsors->count() > 0)
                <ul class="collapsible" data-collapsible="accordion">
                    @foreach($sponsors as $sponsor)
                        <li>
                            <div class="collapsible-header"><i class="material-icons">stars</i> {{ $sponsor->name }}</div>
                            <div class="collapsible-body">
                                <div class="row">
                                    <div class="col s12">
                                        <div class="card z-depth-0">
                                            <div class="card-image">
                                                <img src="{{ $sponsor->mediaURI() }}" alt="LOGO">
                                            </div>
                                            <div class="card-content">
                                                <span class="card-title">Informacion</span>
                                                <p>
                                                    Inicio: {{ $sponsor->valid_from }}
                                                </p>
                                                <p>
                                                    Final: {{ $sponsor->valid_to }}
                                                </p>
                                                <p>
                                                    Zona de display: {{ $sponsor->zone }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    @endforeach
                </ul>
            @else
                <p class="red-text flow-text">No hay sponsors para esta seccion</p>
            @endif
        </div>
    </section>
@endsection

resources/views/helium/sponsors/show.blade.php
@extends('helium.layout')

@section('content')

@endsection